{"uuid": "10d06eba-7967-438f-af41-737f8b7f9a44", "children": ["4e41e6c8-44a6-4423-949a-cf3c515b92eb"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=96.0.4664.110)\n\n", "trace": "  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\tests\\conftest.py\", line 40, in setup\n    actions.sendKeys(lp.getUsername(), \"justin.sirunwa@nihilent.com\")\n  File \"C:\\Selenium\\Selenium-Python-Framework\\pageObjects\\LoginPage.py\", line 15, in getUsername\n    return self.driver.find_element(*LoginPage.username)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1639669551697, "stop": 1639669560306}], "start": 1639669551697, "stop": 1639669572590}