{"uuid": "6db89e60-5c7e-4282-9375-aa1ba25dc45d", "children": ["ad821761-7666-4cfe-8d29-a38999ae2027"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=96.0.4664.110)\n\n", "trace": "  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\tests\\conftest.py\", line 40, in setup\n    actions.sendKeys(lp.getUsername(), \"justin.sirunwa@nihilent.com\")\n  File \"C:\\Selenium\\Selenium-Python-Framework\\pageObjects\\LoginPage.py\", line 15, in getUsername\n    return self.driver.find_element(*LoginPage.username)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1639669429018, "stop": 1639669434090}], "start": 1639669429018, "stop": 1639669434364}